import json

notebook_content = {
    "cells": [
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "import random\n",
                "import os\n",
                "import glob\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "from matplotlib.colors import BoundaryNorm, ListedColormap\n",
                "import matplotlib.patches as mpatches\n",
                "from PIL import Image as PILImage\n",
                "from IPython.display import display, Image as DisplayImage, Markdown\n",
                "from io import BytesIO\n",
                "\n",
                "# ============================================================\n",
                "# Configuration\n",
                "# ============================================================\n",
                "CHIP_DIR = '/explore/nobackup/projects/pix4dcloud/aliewehr/chipTests/newShapeChips/test1'\n",
                "N_CHIPS = 5\n",
                "ABI_BAND = 13\n",
                "FPS = 1.0\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "cloud_colors = [\n",
                "    \"#777777\",  # -1: missing retrieval\n",
                "    \"#ffffff\",  #  0: valid clear\n",
                "    \"#66c2ff\",  #  1 cirrus\n",
                "    \"#33a02c\",  #  2 altostratus\n",
                "    \"#e31a1c\",  #  3 altocumuls\n",
                "    \"#9467bd\",  #  4 stratus\n",
                "    \"#8c564b\",  #  5 stratocumulus\n",
                "    \"#e377c2\",  #  6 cumulus\n",
                "    \"#bcbd22\",  #  7 numbostratus\n",
                "    \"#17becf\",  #  8 deep convection\n",
                "]\n",
                "cloud_cmap = ListedColormap(cloud_colors)\n",
                "cloud_norm = BoundaryNorm(np.arange(-1.5, 9.5, 1), cloud_cmap.N)\n",
                "\n",
                "def draw_legend():\n",
                "    cloud_legend_data = [\n",
                "        (\"-1\", \"#777777\", \"Missing Retrieval\"),\n",
                "        (\"0\", \"#ffffff\", \"Valid Clear\"),\n",
                "        (\"1\", \"#66c2ff\", \"Cirrus\"),\n",
                "        (\"2\", \"#33a02c\", \"Altostratus\"),\n",
                "        (\"3\", \"#e31a1c\", \"Altocumulus\"),\n",
                "        (\"4\", \"#9467bd\", \"Stratus\"),\n",
                "        (\"5\", \"#8c564b\", \"Stratocumulus\"),\n",
                "        (\"6\", \"#e377c2\", \"Cumulus\"),\n",
                "        (\"7\", \"#bcbd22\", \"Nimbostratus\"),\n",
                "        (\"8\", \"#17becf\", \"Deep Convection\"),\n",
                "    ]\n",
                "    patches = []\n",
                "    for val, hex_val, name in cloud_legend_data:\n",
                "        is_white = hex_val == \"#ffffff\"\n",
                "        patches.append(mpatches.Patch(\n",
                "            color=hex_val, label=f\"{val}: {name}\",\n",
                "            edgecolor=\"black\" if is_white else None,\n",
                "            linewidth=0.5 if is_white else 0\n",
                "        ))\n",
                "    fig, ax = plt.subplots(figsize=(6, 4.5), dpi=150)\n",
                "    ax.axis(\"off\")\n",
                "    ax.legend(handles=patches, loc=\"center\", frameon=True, facecolor=\"#f9f9f9\", edgecolor=\"#dddddd\", fontsize=10, title=\"Cloud Color Legend\", title_fontsize=11)\n",
                "    plt.tight_layout()\n",
                "    plt.show()\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "def track_distance_km(latitude, longitude):\n",
                "    latitude = np.deg2rad(latitude)\n",
                "    longitude = np.deg2rad(longitude)\n",
                "    if len(latitude) < 2:\n",
                "        return np.zeros(len(latitude))\n",
                "    delta_latitude = np.diff(latitude)\n",
                "    delta_longitude = np.diff(longitude)\n",
                "    haversine = (\n",
                "        np.sin(delta_latitude / 2) ** 2\n",
                "        + np.cos(latitude[:-1]) * np.cos(latitude[1:])\n",
                "        * np.sin(delta_longitude / 2) ** 2\n",
                "    )\n",
                "    segments = 2 * 6371.0 * np.arcsin(np.sqrt(haversine))\n",
                "    return np.concatenate([[0.0], np.cumsum(segments)])\n",
                "\n",
                "def band_limits(chip, band_index):\n",
                "    values = chip[..., band_index]\n",
                "    valid = values[np.isfinite(values)]\n",
                "    if valid.size == 0:\n",
                "        return 0.0, 1.0\n",
                "    lower, upper = np.percentile(valid, [2, 98])\n",
                "    if np.isclose(lower, upper):\n",
                "        upper = lower + 1.0\n",
                "    return float(lower), float(upper)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "def draw_abi_1d(axis, sample, frame, band_index, limits):\n",
                "    band_1d = sample[\"ABI/chip\"][frame, :, 0, band_index]\n",
                "    distance = track_distance_km(sample[\"CloudSat/latitude\"], sample[\"CloudSat/longitude\"])\n",
                "    maximum_distance = max(float(distance[-1]), 1e-6)\n",
                "    \n",
                "    band_2d = band_1d[np.newaxis, :]\n",
                "    lower, upper = limits\n",
                "    \n",
                "    axis.imshow(\n",
                "        band_2d, origin=\"lower\", aspect=\"auto\",\n",
                "        extent=[0, maximum_distance, 0, 1],\n",
                "        cmap='gray', vmin=lower, vmax=upper\n",
                "    )\n",
                "    \n",
                "    offset = int(sample[\"ABI/offsets_minutes\"][frame])\n",
                "    scan_time = str(sample[\"ABI/scan_times\"][frame])\n",
                "    valid = int(sample[\"ABI/valid_mask\"][frame])\n",
                "    \n",
                "    axis.set_title(f\"ABI C{ABI_BAND:02d} (1D Transect) | {offset:+d} min | valid={valid}\\n{scan_time}\")\n",
                "    axis.set_xlabel(\"Distance along track (km)\")\n",
                "    axis.set_yticks([])\n",
                "    axis.set_ylabel(\"Radiance\")\n",
                "\n",
                "def draw_cloudsat_mask(axis, sample):\n",
                "    mask = sample[\"CloudSat/cloud_class\"]\n",
                "    distance = track_distance_km(sample[\"CloudSat/latitude\"], sample[\"CloudSat/longitude\"])\n",
                "    maximum_distance = max(float(distance[-1]), 1e-6)\n",
                "    \n",
                "    axis.imshow(\n",
                "        mask.T, origin=\"lower\", aspect=\"auto\", interpolation=\"nearest\",\n",
                "        extent=[0, maximum_distance, 0, mask.shape[1] * 0.5],\n",
                "        cmap=cloud_cmap, norm=cloud_norm,\n",
                "    )\n",
                "    axis.set_xlabel(\"Distance along track (km)\")\n",
                "    axis.set_ylabel(\"Altitude (km)\")\n",
                "    axis.set_ylim(0, 20)\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "def make_gif(path):\n",
                "    sample = np.load(path, allow_pickle=True)\n",
                "    band_index = ABI_BAND - 1\n",
                "    limits = band_limits(sample[\"ABI/chip\"], band_index)\n",
                "    fileName = path.split('/')[-1]\n",
                "    frames = []\n",
                "    \n",
                "    for frame in range(sample[\"ABI/chip\"].shape[0]):\n",
                "        figure, axes = plt.subplots(2, 1, figsize=(14, 8), dpi=90, gridspec_kw={'height_ratios': [1, 3]})\n",
                "        draw_abi_1d(axes[0], sample, frame, band_index, limits)\n",
                "        draw_cloudsat_mask(axes[1], sample)\n",
                "        figure.suptitle(fileName, fontsize=10)\n",
                "        figure.tight_layout(rect=(0, 0, 1, 0.95))\n",
                "        figure.canvas.draw()\n",
                "        image = PILImage.fromarray(np.asarray(figure.canvas.buffer_rgba())).convert(\"RGB\")\n",
                "        frames.append(image)\n",
                "        plt.close(figure)\n",
                "        \n",
                "    buffer = BytesIO()\n",
                "    frames[0].save(\n",
                "        buffer, format=\"GIF\", save_all=True, append_images=frames[1:],\n",
                "        duration=int(1000 / FPS), loop=0, disposal=2, optimize=False,\n",
                "    )\n",
                "    return buffer.getvalue()\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "source": [
                "chip_files = sorted(glob.glob(os.path.join(CHIP_DIR, \"*.npz\")))\n",
                "if not chip_files:\n",
                "    raise FileNotFoundError(f\"No NPZ files found in {CHIP_DIR}\")\n",
                "\n",
                "# Pick random chips\n",
                "selected_files = random.sample(chip_files, k=min(N_CHIPS, len(chip_files)))\n",
                "print(f\"Displaying {len(selected_files)} random chips of {len(chip_files)} total.\")\n",
                "\n",
                "draw_legend()\n",
                "\n",
                "for chip_number, path in enumerate(selected_files, start=1):\n",
                "    display(Markdown(f\"### Chip {chip_number}/{len(selected_files)}\\n**{os.path.basename(path)}**\"))\n",
                "    gif_data = make_gif(path)\n",
                "    display(DisplayImage(data=gif_data, format=\"gif\"))\n"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("presentable_vis.ipynb", "w") as f:
    json.dump(notebook_content, f, indent=1)
